name: Latest Spyglass Docker Build

on:
  workflow_dispatch:

# For debugging
# on:
#   push:
#     branches: ''

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t swirlai/spyglass:latest  -f Dockerfile.spg .
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: docker push swirlai/spyglass
